apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: yo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: yo
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
      - name: BP_NATIVE_IMAGE
        value: "true"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/doddatpivotal/yo
      ref:
        branch: main
